version: '3'
services:
  backend:
    image: "reepovv/poems-server-js:latest"
    container_name: backend
    restart: unless-stopped
    ports:
      - "80:3333"
    networks:
      - app-network
  postgres:
    image: "postgres:13.0"
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB: postgres
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_USER: postgres
    networks:
      - app-network
  networks:
    app-network:
      driver: bridge