const UUIDV4 =  require('uuid');
const multer = require('multer');
const express = require('express');
const bodyParser = require('body-parser');
const { Sequelize } = require('sequelize');
const User = require('../express-server/Models/UserModel');
const Poems = require('../express-server/Models/PoemsModel');
const UserViewModel = require('../express-server/ViewModels/UserViewModel');
const PoemsViewModel = require('../express-server/ViewModels/PoemsViewModel');
const UserController = require('../express-server/Controllers/UserController');
const PoemsController = require('../express-server/Controllers/PoemsController');
const db = new Sequelize('postgresql://postgres:postgres@185.119.56.91:5432/postgres');

const port = 3333;
const app = express();
const upload = multer();
app.use(upload.array()); 
const host = 'localhost';
app.use(bodyParser.json()); 
app.use(express.static('public'));
app.use('/api/User/', UserController);
app.use('/api/Poems/', PoemsController);
app.use(bodyParser.urlencoded({ extended: true }));
app.listen(port, () => console.log('Application listening on port 3333!'));